// Noticias y eventos institucionales — editar aquí para actualizar el feed
export const noticias = [
  {
    id: 1,
    categoria: 'Publicación Científica',
    categoriaColor: 'bg-[#12377B] text-white',
    titulo: 'Modelos de interpolación espacial para los movimientos sísmicos del Perú',
    resumen: 'Análisis geoestadístico de 2602 registros sísmicos del IGP (2020–2023) mediante modelos de interpolación espacial. Trabajo conjunto de L. A. Rubio Jácobo, E. Ipanaqué Centeno, Y. N. Rosas Reyes y C. F. Julián Rodríguez.',
    fecha: '2025-06-15',
    fechaFormateada: '15 Jun 2025',
    link: '/investigacion/publicaciones',
    imagen: '',
  },
  {
    id: 2,
    categoria: 'Publicación Científica',
    categoriaColor: 'bg-[#12377B] text-white',
    titulo: 'Efecto de los lazos parentales en la autoestima de estudiantes de la FCFYM',
    resumen: 'Estudio observacional descriptivo que determina el efecto de los lazos parentales en la autoestima de 191 estudiantes de la UNT. Autores: R. Gutiérrez de Alarcón, M. L. Cuadra Moreno, R. Alarcón Gutiérrez, S. Sánchez Pereda y C. G. Alarcón Gutiérrez.',
    fecha: '2025-06-10',
    fechaFormateada: '10 Jun 2025',
    link: '/investigacion/publicaciones',
    imagen: '',
  },
  {
    id: 3,
    categoria: 'Tesis y Proyectos',
    categoriaColor: 'bg-[#E6AC09] text-[#1B1711]',
    titulo: 'Modelización Econométrica Data Panel de la Inversión Extranjera Directa en el PBI de países ALADI, 2000-2023',
    resumen: 'Investigación econométrica de datos de panel que analiza el impacto de la Inversión Extranjera Directa sobre el PBI. Tesis de Milton Giancarlo Medina Ascón, asesorada por la Dra. Daphne Jannet Timaná Palacios.',
    fecha: '2025-05-28',
    fechaFormateada: '28 May 2025',
    link: '/investigacion/proyectos',
    imagen: '',
  },
  {
    id: 4,
    categoria: 'Tesis y Proyectos',
    categoriaColor: 'bg-[#E6AC09] text-[#1B1711]',
    titulo: 'Un modelo de data panel de la contribución del turismo en el PBI de los países de Sudamérica',
    resumen: 'Investigación que evalúa la contribución del turismo en el PBI de los países de Sudamérica (2000–2019). Tesis de Marisol Alessandra García Tejeda, asesorada por la Dra. Daphne Jannet Timaná Palacios.',
    fecha: '2025-05-20',
    fechaFormateada: '20 May 2025',
    link: '/investigacion/proyectos',
    imagen: '',
  },
];
