// Noticias y eventos institucionales — editar aquí para actualizar el feed
export const noticias = [
  {
    id: 1,
    categoria: 'Evento Académico',
    categoriaColor: 'bg-[#12377B] text-white',
    titulo: 'Noticia 1',
    resumen: 'Próximamente se publicará información detallada sobre esta actividad académica del programa.',
    fecha: '2025-06-15',
    fechaFormateada: '15 Jun 2025',
    link: '#',
    imagen: '',
  },
  {
    id: 2,
    categoria: 'Convocatoria',
    categoriaColor: 'bg-[#E6AC09] text-[#1B1711]',
    titulo: 'Noticia 2',
    resumen: 'Próximamente se publicará información detallada sobre esta convocatoria de prácticas preprofesionales.',
    fecha: '2025-06-10',
    fechaFormateada: '10 Jun 2025',
    link: '#',
    imagen: '',
  },
  {
    id: 3,
    categoria: 'Logro Institucional',
    categoriaColor: 'bg-[#000C4A] text-white',
    titulo: 'Noticia 3',
    resumen: 'Próximamente se publicará información detallada sobre este logro e infraestructura de la escuela.',
    fecha: '2025-05-28',
    fechaFormateada: '28 May 2025',
    link: '#',
    imagen: '',
  },
  {
    id: 4,
    categoria: 'Aviso',
    categoriaColor: 'bg-[#12377B] text-white',
    titulo: 'Noticia 4',
    resumen: 'Próximamente se publicará información detallada sobre este comunicado y aviso de interés estudiantil.',
    fecha: '2025-05-20',
    fechaFormateada: '20 May 2025',
    link: '#',
    imagen: '',
  },
  {
    id: 5,
    categoria: 'Comunicado',
    categoriaColor: 'bg-[#E6AC09] text-[#1B1711]',
    titulo: 'Noticia 5',
    resumen: 'Próximamente se publicará información detallada sobre este comunicado de la Escuela de Estadística.',
    fecha: '2025-05-15',
    fechaFormateada: '15 May 2025',
    link: '#',
    imagen: '',
  },
];
